name: Test

on: [push]

jobs: 
  test-build:
    runs-on: ubuntu-latest

    steps:          
      - name: Checkout
        uses: actions/checkout@v4.2.0
      - name: lss
        run: |
         chmod +x script.sh
         ./scripst.sh
